#!/usr/bin/env bash

# ==============================================================================
# Strict Bash Mode
# ==============================================================================
set -euo pipefail
trap 'echo -e "\033[0;31mERROR in ${BASH_SOURCE[0]} at line ${LINENO}: ${BASH_COMMAND}\033[0m" >&2' ERR

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${YELLOW}Starting Modern Webmail Deployment...${NC}"

source ./config.conf
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_DIR=$(cd "${SCRIPT_DIR}/.." && pwd)
source "${SCRIPT_DIR}/lib_os.sh"
detect_openmailstack_os

BACKEND_SRC="${REPO_DIR}/webmail-backend"
FRONTEND_SRC="${REPO_DIR}/webmail-frontend"
BACKEND_DIR="/opt/openmailstack-backend"
FRONTEND_DIR="${OPENMAILSTACK_WEB_ROOT:-/var/www/openmailstack}"
ENV_DIR="/etc/openmailstack"
ENV_FILE="${ENV_DIR}/webmail-backend.env"
SERVICE_FILE="/etc/systemd/system/openmailstack.service"
NGINX_CONF="/etc/nginx/sites-available/mailserver.conf"
WEBMAIL_USER="openmailstack"
WEBMAIL_GROUP="openmailstack"
WEBMAIL_HOST="${OMS_WEBMAIL_HOST:-127.0.0.1}"
WEBMAIL_PORT="${OMS_WEBMAIL_PORT:-20000}"
PUBLIC_BASE_URL="${OMS_PUBLIC_BASE_URL:-https://${MAIL_HOSTNAME}}"
DEFAULT_DOMAIN="${OMS_DEFAULT_DOMAIN:-${FIRST_DOMAIN}}"

require_path() {
    local path="$1"
    if [[ ! -e "${path}" ]]; then
        echo -e "${RED}Error: Required path not found: ${path}${NC}" >&2
        exit 1
    fi
}

write_env_line() {
    local key="$1"
    local value="$2"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '%s="%s"\n' "${key}" "${value}"
}

install_node_toolchain() {
    echo -e "Installing Node.js/npm and deployment helpers..."
    openmailstack_install_required_packages nodejs npm rsync

    if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
        echo -e "${RED}Error: node and npm are required for modern webmail deployment.${NC}" >&2
        exit 1
    fi

    local node_version major minor patch
    node_version="$(node -p 'process.versions.node')"
    IFS='.' read -r major minor patch <<< "${node_version}"
    if (( major < 20 || (major == 20 && minor < 19) )); then
        echo -e "${RED}Error: Modern webmail requires Node.js >= 20.19.0 for the current Vite stack; found ${node_version}.${NC}" >&2
        echo -e "${YELLOW}Install a current Node.js LTS package and rerun this module.${NC}" >&2
        exit 1
    fi
}

npm_install_for_build() {
    local app_dir="$1"
    cd "${app_dir}"
    if [[ -f package-lock.json ]]; then
        npm ci
    else
        npm install
    fi
}

ensure_service_user() {
    if ! getent group "${WEBMAIL_GROUP}" >/dev/null; then
        groupadd --system "${WEBMAIL_GROUP}"
    fi
    if ! getent passwd "${WEBMAIL_USER}" >/dev/null; then
        useradd --system --gid "${WEBMAIL_GROUP}" --home-dir "${BACKEND_DIR}" --shell /usr/sbin/nologin "${WEBMAIL_USER}"
    fi
}

render_backend_env() {
    echo -e "Writing ${ENV_FILE}..."
    install -d -m 0700 "${ENV_DIR}"
    umask 077
    {
        echo "# Generated by OpenMailStack functions/10_webmail.sh"
        write_env_line "OMS_WEBMAIL_HOST" "${WEBMAIL_HOST}"
        write_env_line "OMS_WEBMAIL_PORT" "${WEBMAIL_PORT}"
        write_env_line "OMS_PUBLIC_BASE_URL" "${PUBLIC_BASE_URL}"
        write_env_line "OMS_DEFAULT_DOMAIN" "${DEFAULT_DOMAIN}"
        write_env_line "OMS_COOKIE_SECURE" "${OMS_COOKIE_SECURE:-true}"
        write_env_line "OMS_UPLOAD_LIMIT_BYTES" "${OMS_UPLOAD_LIMIT_BYTES:-26214400}"
        write_env_line "OMS_DB_HOST" "${OMS_DB_HOST:-127.0.0.1}"
        write_env_line "OMS_DB_PORT" "${OMS_DB_PORT:-3306}"
        write_env_line "OMS_DB_USER" "${OMS_DB_USER:-${POSTFIXADMIN_DB_USER}}"
        write_env_line "OMS_DB_PASSWORD" "${OMS_DB_PASSWORD:-${POSTFIXADMIN_DB_PASSWORD}}"
        write_env_line "OMS_DB_NAME" "${OMS_DB_NAME:-${POSTFIXADMIN_DB_NAME}}"
        write_env_line "OMS_DB_CONNECTION_LIMIT" "${OMS_DB_CONNECTION_LIMIT:-10}"
        write_env_line "OMS_IMAP_HOST" "${OMS_IMAP_HOST:-127.0.0.1}"
        write_env_line "OMS_IMAP_PORT" "${OMS_IMAP_PORT:-143}"
        write_env_line "OMS_IMAP_SECURE" "${OMS_IMAP_SECURE:-false}"
        write_env_line "OMS_IMAP_REJECT_UNAUTHORIZED" "${OMS_IMAP_REJECT_UNAUTHORIZED:-true}"
        write_env_line "OMS_SMTP_HOST" "${OMS_SMTP_HOST:-127.0.0.1}"
        write_env_line "OMS_SMTP_PORT" "${OMS_SMTP_PORT:-587}"
        write_env_line "OMS_SMTP_SECURE" "${OMS_SMTP_SECURE:-false}"
        write_env_line "OMS_SMTP_REJECT_UNAUTHORIZED" "${OMS_SMTP_REJECT_UNAUTHORIZED:-true}"
        write_env_line "OMS_SIEVE_HOST" "${OMS_SIEVE_HOST:-127.0.0.1}"
        write_env_line "OMS_SIEVE_PORT" "${OMS_SIEVE_PORT:-4190}"
    } > "${ENV_FILE}"
    chown root:root "${ENV_FILE}"
    chmod 0600 "${ENV_FILE}"
}

deploy_backend() {
    echo -e "Building and deploying webmail backend..."
    npm_install_for_build "${BACKEND_SRC}"
    npm --prefix "${BACKEND_SRC}" run build

    ensure_service_user
    install -d -o "${WEBMAIL_USER}" -g "${WEBMAIL_GROUP}" -m 0755 "${BACKEND_DIR}"
    rsync -a --delete \
        --exclude node_modules \
        --exclude .npm \
        "${BACKEND_SRC}/" "${BACKEND_DIR}/"

    cd "${BACKEND_DIR}"
    if [[ -f package-lock.json ]]; then
        npm ci --omit=dev
    else
        npm install --omit=dev
    fi
    chown -R "${WEBMAIL_USER}:${WEBMAIL_GROUP}" "${BACKEND_DIR}"

    render_backend_env
    install -m 0644 "${REPO_DIR}/packaging/systemd/openmailstack.service" "${SERVICE_FILE}"
    systemctl daemon-reload
    systemctl enable --now openmailstack.service
    systemctl restart openmailstack.service
}

deploy_frontend() {
    echo -e "Building and deploying webmail frontend..."
    npm_install_for_build "${FRONTEND_SRC}"
    npm --prefix "${FRONTEND_SRC}" run build

    install -d -m 0755 "${FRONTEND_DIR}"
    rsync -a --delete "${FRONTEND_SRC}/dist/" "${FRONTEND_DIR}/"
    chown -R root:root "${FRONTEND_DIR}"
    find "${FRONTEND_DIR}" -type d -exec chmod 755 {} \;
    find "${FRONTEND_DIR}" -type f -exec chmod 644 {} \;
}

configure_nginx() {
    echo -e "Configuring Nginx for modern webmail..."
    require_path "${NGINX_CONF}"

    local tmp snippet
    tmp="$(mktemp)"
    snippet="$(mktemp)"

    sed '/# --- OpenMailStack Modern Webmail ---/,/# --- End OpenMailStack Modern Webmail ---/d' "${NGINX_CONF}" > "${tmp}"
    mv "${tmp}" "${NGINX_CONF}"

    cat > "${snippet}" <<EOF
    # --- OpenMailStack Modern Webmail ---
    client_max_body_size 50m;

    location ^~ /api/ {
        proxy_pass http://${WEBMAIL_HOST}:${WEBMAIL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 1h;
    }

    location = /api {
        proxy_pass http://${WEBMAIL_HOST}:${WEBMAIL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location = /rspamd {
        return 301 /rspamd/;
    }

    location ^~ /rspamd/ {
        proxy_pass http://127.0.0.1:11334/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering off;
        proxy_read_timeout 1h;
    }

    location ^~ /caldav {
        proxy_pass http://${WEBMAIL_HOST}:${WEBMAIL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location ^~ /carddav {
        proxy_pass http://${WEBMAIL_HOST}:${WEBMAIL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location ~* ^/autodiscover/autodiscover\\.xml$ {
        proxy_pass http://${WEBMAIL_HOST}:${WEBMAIL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location = /Microsoft-Server-ActiveSync {
        proxy_pass http://${WEBMAIL_HOST}:${WEBMAIL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 1h;
    }

    location = /.well-known/caldav {
        proxy_pass http://${WEBMAIL_HOST}:${WEBMAIL_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location = /.well-known/carddav {
        proxy_pass http://${WEBMAIL_HOST}:${WEBMAIL_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        if ($request_method ~ ^(PROPFIND|OPTIONS)$) {
            return 301 /caldav/;
        }
        root ${FRONTEND_DIR};
        try_files \$uri \$uri/ /index.html;
    }
    # --- End OpenMailStack Modern Webmail ---
EOF

    awk -v snippet="${snippet}" '
        /^}[[:space:]]*$/ && !inserted {
            while ((getline line < snippet) > 0) {
                print line
            }
            close(snippet)
            inserted = 1
        }
        { print }
    ' "${NGINX_CONF}" > "${tmp}"
    mv "${tmp}" "${NGINX_CONF}"
    rm -f "${snippet}"

    nginx -t
    systemctl reload nginx || systemctl restart nginx
}

require_path "${BACKEND_SRC}"
require_path "${FRONTEND_SRC}"
require_path "${REPO_DIR}/packaging/systemd/openmailstack.service"

install_node_toolchain
deploy_frontend
deploy_backend
configure_nginx

echo -e "${GREEN}Modern webmail deployment complete!${NC}"
