CREATE TABLE IF NOT EXISTS mail_import_jobs (
 id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 owner VARCHAR(255) NOT NULL,
 source_name VARCHAR(255) NOT NULL,
 source_sha256 CHAR(64) CHARACTER SET ascii NOT NULL,
 source_bytes INT UNSIGNED NOT NULL,
 folder TEXT NOT NULL,
 uid_validity VARCHAR(32) NOT NULL,
 destination_sha256 CHAR(64) CHARACTER SET ascii NOT NULL,
 manifest_json MEDIUMTEXT NOT NULL,
 total INT UNSIGNED NOT NULL,
 cursor_index INT UNSIGNED NOT NULL DEFAULT 0,
 imported INT UNSIGNED NOT NULL DEFAULT 0,
 skipped INT UNSIGNED NOT NULL DEFAULT 0,
 state VARCHAR(16) NOT NULL DEFAULT 'ready',
 last_error VARCHAR(512) NULL,
 staged TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 KEY import_owner (owner)
);
CREATE TABLE IF NOT EXISTS mail_import_receipts (
 destination_sha256 CHAR(64) CHARACTER SET ascii NOT NULL,
 message_sha256 CHAR(64) CHARACTER SET ascii NOT NULL,
 state VARCHAR(16) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (destination_sha256, message_sha256)
);
