const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
test('P2 import resumes after lost acknowledgements, deduplicates and isolates owners; Notes Trash preserves dependents', { skip: process.env.OMS_P2_DB_TEST !== '1' }, async t => {
 assert.match(process.env.OMS_DB_NAME || '', /^oms_p2_[a-f0-9]+$/);
 const {pool}=require('../src/db.js'); t.after(()=>pool.end());
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'oms-p2-import-')); t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const {createMailImportRouter}=require('../src/mail-import.js');
 let owner='p2-owner@example.test', validity='77', loseAck=false; const appended=[];
 const imap={client:{getMailboxLock:async()=>({release(){}}),get mailbox(){return {uidValidity:validity};},search:async query=>appended.map((raw,i)=>raw.includes(query.header['x-oms-import-id'])?i+1:0).filter(Boolean),append:async(_folder,raw)=>{appended.push(raw.toString());if(loseAck){loseAck=false;throw new Error('Lost acknowledgement');}return {uid:appended.length};}}};
 const express=require('express'); const app=express();app.use(express.json());app.use((req,_res,next)=>{req.user={username:owner,password:'fixture'};next();});app.use('/import',createMailImportRouter(async(_owner,_pass,work)=>work(imap),root));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});
 const url=`http://127.0.0.1:${server.address().port}/import`;
 const call=async(suffix='',body,method='POST')=>{const response=await fetch(url+suffix,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return {status:response.status,...await response.json()};};
 const eml=n=>`From: sender@example.test\r\nSubject: Message ${n}\r\nMessage-ID: <${n}@example.test>\r\n\r\nBody ${n}\r\n`;
 const prepare=async(n,name='mail.eml')=>{const form=new FormData();form.append('folder','Imported');form.append('file',new Blob([n]),name);const response=await fetch(url,{method:'POST',body:form});assert.equal(response.status,200);return (await response.json()).job;};
 const job=await prepare(eml(1)); assert.equal(appended.length,0,'review does not append');
 assert.equal((await prepare(eml(1))).id,job.id);
 owner='p2-stranger@example.test';assert.equal((await call(`/${job.id}/run`,{confirm:true,cursor:0})).status,409);owner='p2-owner@example.test';
 loseAck=true;assert.equal((await call(`/${job.id}/run`,{confirm:true,cursor:0})).status,409);assert.equal(appended.length,1);
 const resumed=await call(`/${job.id}/run`,{confirm:true,cursor:0});assert.equal(resumed.job.state,'complete');assert.equal(resumed.job.skipped,1);assert.equal(appended.length,1);
 assert.equal((await fs.readdir(root)).length,0,'completed source removed');
 const mbox=Array.from({length:12},(_,i)=>`From sender@example.test Mon Sep 14 10:00:00 2026\r\n${eml(i+1)}`).join('');
 const batch=await prepare(mbox,'mail.mbox');
 const first=await call(`/${batch.id}/run`,{confirm:true,cursor:0});assert.equal(first.job.cursor,10);assert.equal(first.job.skipped,1);
 assert.equal((await call(`/${batch.id}/run`,{confirm:true,cursor:0})).job.cursor,10,'old cursor only replays progress');
 assert.equal((await call(`/${batch.id}/run`,{confirm:true,cursor:10})).job.state,'complete');assert.equal(appended.length,12);
 const cleanup=await prepare(eml(30));const unlink=fs.unlink;let failCleanup=true;
 fs.unlink=async target=>{if(failCleanup && String(target).endsWith(cleanup.id+'.mail')){failCleanup=false;throw new Error('Temporary cleanup failure');}return unlink(target);};
 try {assert.equal((await call(`/${cleanup.id}/run`,{confirm:true,cursor:0})).status,409);}finally{fs.unlink=unlink;}
 let history=await call('',undefined,'GET');let pendingCleanup=history.jobs.find(job=>job.id===cleanup.id);assert.equal(pendingCleanup.state,'complete');assert.equal(pendingCleanup.staged,true);
 const appendCount=appended.length;assert.equal((await call(`/${cleanup.id}/run`,{confirm:true,cursor:1})).job.staged,false);assert.equal(appended.length,appendCount);
 await call(`/${cleanup.id}`,{confirm:true},'DELETE');history=await call('',undefined,'GET');assert.equal(history.jobs.find(job=>job.id===cleanup.id).state,'complete');
 const changed=await prepare(eml(20));validity='78';assert.equal((await call(`/${changed.id}/run`,{confirm:true,cursor:0})).status,409);assert.equal(appended.length,13);validity='77';
 assert.equal((await call(`/${changed.id}`,{confirm:true},'DELETE')).success,true);assert.equal(appended.length,13,'cancelling never removes imported mail');
 const indexPath=require.resolve('../src/index.js');require.cache[indexPath]={id:indexPath,filename:indexPath,loaded:true,exports:{io:{to:()=>({emit(){}})}}};
 const notes=require('../src/notes-utils.js');await notes.ensureNotesSchema();await notes.ensureRemindersSchema();await notes.ensureAttachmentsSchema();
 const uploadRoot=path.resolve(__dirname,'../uploads');await fs.mkdir(uploadRoot,{recursive:true});const attachment=await fs.mkdtemp(path.join(uploadRoot,'p2-note-'));t.after(()=>fs.rm(attachment,{recursive:true,force:true}));const attachmentFile=path.join(attachment,'fixture.txt');await fs.writeFile(attachmentFile,'Retain attachment');
 const id='p2-note';await pool.query('INSERT INTO notes (id,owner,title,content) VALUES (?,?,?,?)',[id,owner,'Restore me','<p>Body</p>']);
 await pool.query('INSERT INTO note_attachments (id,note_id,filename,mime_type,size_bytes,storage_path) VALUES (?,?,?,?,?,?)',['p2-att',id,'fixture.txt','text/plain',17,path.relative(uploadRoot,attachmentFile)]);
 await pool.query('INSERT INTO note_reminders (note_id,remind_at) VALUES (?,DATE_SUB(NOW(),INTERVAL 1 DAY))',[id]);
 await pool.query('UPDATE notes SET imap_uid=55,imap_msgid=? WHERE id=?',['linked@example.test',id]);
 await notes.deleteNote(id,owner);
 let [rows]=await pool.query('SELECT * FROM note_reminders WHERE note_id=?',[id]);assert.equal(rows.length,1);
 await assert.rejects(notes.restoreNote(id,'p2-stranger@example.test'),/unavailable/);
 await notes.restoreNote(id,owner);[rows]=await pool.query('SELECT * FROM notes WHERE id=?',[id]);assert.equal(rows[0].is_deleted,0);assert.equal(rows[0].content,'<p>Body</p>');assert.equal(rows[0].imap_uid,55);assert.equal(rows[0].imap_msgid,'linked@example.test');assert.equal(await fs.readFile(attachmentFile,'utf8'),'Retain attachment');
 [rows]=await pool.query('SELECT * FROM note_reminders WHERE note_id=?',[id]);assert.equal(rows[0].notified,1);
 await assert.rejects(notes.purgeNote(id,owner),/Trash/);await notes.deleteNote(id,owner);await notes.purgeNote(id,owner);
 [rows]=await pool.query('SELECT * FROM notes WHERE id=?',[id]);assert.equal(rows[0].is_purged,1);assert.equal(rows[0].content,'');await assert.rejects(fs.stat(attachmentFile),{code:'ENOENT'});
 [rows]=await pool.query('SELECT * FROM note_reminders WHERE note_id=?',[id]);assert.equal(rows.length,0);await assert.rejects(notes.restoreNote(id,owner),/unavailable/);
});
